In [3]:
import pandas as pd 
import numpy as np

df = pd.DataFrame({
    "ID": ["C1", "C2", "C3", "C4", "C5","C6","C7","C8","C9","C10"], 
    "City": ["Lampung", "Jakarta", "Bogor", "Tanggerang", "Cikarang", "Bandung", "Surabaya", "Medan", "Semarang", "Yogyakarta"], 
    "Value": [3, 6, 9, 9, 7, 5, 8, 4, 6, 7]  
})
print(df)

    ID        City  Value
0   C1     Lampung      3
1   C2     Jakarta      6
2   C3       Bogor      9
3   C4  Tanggerang      9
4   C5    Cikarang      7
5   C6     Bandung      5
6   C7    Surabaya      8
7   C8       Medan      4
8   C9    Semarang      6
9  C10  Yogyakarta      7

# DF Info

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ID      10 non-null     object
 1   City    10 non-null     object
 2   Value   10 non-null     int64
dtypes: int64(1), object(2)
memory usage: 372.0+ bytes

# Statistic Numeric

In [7]:
df

    ID        City  Value
0   C1     Lampung      3
1   C2     Jakarta      6
2   C3       Bogor      9
3   C4  Tanggerang      9
4   C5    Cikarang      7
5   C6     Bandung      5
6   C7    Surabaya      8
7   C8       Medan      4
8   C9    Semarang      6
9  C10  Yogyakarta      7

In [8]:
df.describe()

          Value
count  10.00000
mean    6.40000
std     2.01108
min     3.00000
25%     5.25000
50%     6.50000
75%     7.75000
max     9.00000