In [3]:
import pandas as pd

df = pd.read_csv("../Pandas_DF/data.csv")
print(df)

    ID        City  Value
0   C1     Lampung      3
1   C2     Jakarta      6
2   C3       Bogor      9
3   C4  Tanggerang      9
4   C5    Cikarang      7
5   C6     Bandung      5
6   C7    Surabaya      8
7   C8       Medan      4
8   C9    Semarang      6
9  C10  Yogyakarta      7

## Data Index Filtering

In [ ]:
df.iloc[0]["City"]   ## Single value

'Lampung'

In [ ]:
df.iloc[0:3]        ## Multiple rows range value

   ID     City  Value
0  C1  Lampung      3
1  C2  Jakarta      6
2  C3    Bogor      9

In [33]:
df.iloc[0:3][["City","Value"]]        ## Multiple rows multiple columns

      City  Value
0  Lampung      3
1  Jakarta      6
2    Bogor      9

# Filtering Using Criteria

In [40]:
df

    ID        City  Value
0   C1     Lampung      3
1   C2     Jakarta      6
2   C3       Bogor      9
3   C4  Tanggerang      9
4   C5    Cikarang      7
5   C6     Bandung      5
6   C7    Surabaya      8
7   C8       Medan      4
8   C9    Semarang      6
9  C10  Yogyakarta      7

In [ ]:
df[(df["City"] == "Lampung")]

   ID     City  Value
0  C1  Lampung      3

In [66]:
df[(df["Value"] <= 5)]

   ID     City  Value
0  C1  Lampung      3
5  C6  Bandung      5
7  C8    Medan      4

In [70]:
df[~(df["Value"] <= 5)]

    ID        City  Value
1   C2     Jakarta      6
2   C3       Bogor      9
3   C4  Tanggerang      9
4   C5    Cikarang      7
6   C7    Surabaya      8
8   C9    Semarang      6
9  C10  Yogyakarta      7

In [77]:
df[(df["Value"] >= 5) & (df["City"] == "Surabaya")]

   ID      City  Value
6  C7  Surabaya      8

In [88]:
list_city = ["Bogor", "Yogyakarta", "Semarang", "Surabaya", "Bandung", "Medan", "Makassar", "Palembang", "Denpasar", "Balikpapan"]

df[
    (df["City"].isin(list_city)) &
    (df["Value"] >= 5)
]

    ID        City  Value
2   C3       Bogor      9
5   C6     Bandung      5
6   C7    Surabaya      8
8   C9    Semarang      6
9  C10  Yogyakarta      7